"""Generate relationships between users and posts

Revision ID: 2863896d93bc
Revises: 97d8c76499ca
Create Date: 2023-07-11 18:58:38.581426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2863896d93bc'
down_revision = '97d8c76499ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'issues', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'owner_id')
    # ### end Alembic commands ###
