"""Add Teams table

Revision ID: d8273231a2c4
Revises: 2863896d93bc
Create Date: 2023-09-05 13:04:46.762891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8273231a2c4'
down_revision = '2863896d93bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_teams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.add_column('issues', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('issues_owner_id_fkey', 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['assigned_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'issues', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('issues', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key('issues_owner_id_fkey', 'issues', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('issues', 'team_id')
    op.drop_column('issues', 'assigned_user_id')
    op.drop_table('user_teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
